name: JMeter Performance CI

on:
  push:
    branches: [ main ]

permissions:
  contents: write # Necessário para o bot postar o relatório no branch gh-pages

jobs:
  performance-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Configurar Java
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Instalar Apache JMeter
        run: |
          wget https://archive.apache.org/dist/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz
          echo "$(pwd)/apache-jmeter-5.6.3/bin" >> $GITHUB_PATH

      - name: Rodar Teste de Performance
        run: |
          mkdir -p reports/dashboard
          # O comando abaixo roda o teste e gera o HTML
          jmeter -n -t scripts/desafioActPerformance.jmx -l results.jtl -e -o reports/dashboard/

      - name: Publicar no GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./reports/dashboard # Publica apenas o conteúdo da pasta do relatório